version: '3.17'

networks:
  stationery_network:
    driver: bridge

services:
  stationery-app:
    container_name: stationery-app
    image: ${IMAGE_NAME}
    ports:
      - '88:88'
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 88 --reload
    networks:
      - stationery_network
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5454:5432"
    networks:
      - stationery_network

  migration:
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    image: ${IMAGE_NAME}:latest
    networks:
      - stationery_network
    entrypoint: /bin/sh -c "dbmate wait && dbmate up"
    depends_on:
      - db


volumes:
    db_data:
